all:
  children:
    sec_cloud:
      hosts:
        thehive_server:
          ansible_host: "{{ thehive_private_ip }}"
        misp_server:
          ansible_host: "{{ misp_private_ip }}"
      vars:
        ansible_user: ec2-user
        ansible_ssh_private_key_file: "{{ ssh_key_path }}"
        ansible_ssh_common_args: >
          -o StrictHostKeyChecking=no
          -o ProxyCommand="ssh -W %h:%p -q ec2-user@{{ nat_public_ip }} -i {{ ssh_key_path }}"

    home_servers:
      hosts:
        wazuh_manager:
          ansible_host: "{{ wazuh_tailscale_ip }}"
      vars:
        ansible_user: "{{ home_user }}"