---
- name: Wazuh Manager 설치
  shell: |
    if [ ! -f /var/ossec/bin/wazuh-control ]; then
      curl -sO https://packages.wazuh.com/4.x/wazuh-install.sh && bash ./wazuh-install.sh -a
    fi
  args:
    creates: /var/ossec/bin/wazuh-control # 이미 설치되어 있으면 건너뜀

- name: MISP 연동 스크립트 배포
  template:
    src: custom-misp.py.j2
    dest: /var/ossec/integrations/custom-misp.py
    owner: root
    group: wazuh
    mode: '0750' # 실행 권한 

- name: OSSEC 설정에 MISP 연동 블록 추가
  blockinfile:
    path: /var/ossec/etc/ossec.conf
    insertafter: "<ossec_config>"
    marker: ""
    block: |
      <integration>
        <name>custom-misp</name>
        <hook_url>http://{{ misp_private_ip }}:8080/events/restSearch</hook_url>
        <api_key>{{ misp_api_key }}</api_key>
        <alert_format>json</alert_format>
      </integration>

- name: Wazuh Manager 재시작
  service:
    name: wazuh-manager
    state: restarted